volumes:
  postgres-data:


services:
  kvak:
    build: ./kvak
    working_dir: /app
    command: ./manage.py runserver 0.0.0.0:8000
    user: "wagtail:wagtail"
    volumes:
      - ./kvak:/app:delegated,rw
      - ./kvak/ipython_config.py:/tmp/ipython/profile_default/ipython_config.py:delegated,rw
    ports:
      - "8000:8000"
    environment:
      DJANGO_RUNSERVER_HIDE_WARNING: "true"
      DJANGO_DATABASE_HOST: db
      DJANGO_DATABASE_NAME: kvak
      DJANGO_DATABASE_USERNAME: kvak
      DJANGO_DATABASE_PASSWORD: changeme
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: kvak
      POSTGRES_USER: kvak
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
